### ISSUE TITLE
2014-07-01-Todo list

### ISSUE THREAD

**Issue by Jayin** [Jayin/jayin.github.io#33]
### 近期完成：
1. ETips 3.0
2. 个人博客：更简单，适配手机
3. 个人项目发布模板
4. A file watching service. see @facebook/watchman

### 中期目标
1. 邑点通微信后台开发[暂时没啥想法]

### 较长时间完成
1. EManual for java & python (backend?)
2. 团队协作工具
3. [may be]enhance IMS 2.0
4. [may be]基于社区管理/社交

### ETips 3.0 to-do 
1. 内置浏览器(方便消息整理通知,论坛)
2  加入全新后台支持，后台请求课表/成绩/新闻，添加缓存
3. 图书馆模块：
	3.1. 个人借阅历史/借阅到期提醒
	3.2. 想借阅的书的到期提醒
	3.2. 图书评论
4. 课表模块
	4.1 从新设计课表,支持更换背景[考虑中]
	4.2 课程提醒
	4.3 支持课程添加，删除
5. 新闻模块
	5.1. 支持评论[考虑中]
6. 移除个人便签
7. Material Design

config file:
app url + form url + update time

### 个人项目发布模板
1. 全力拥抱Markdown
2. 参考亮爷的[silent](https://github.com/fritx/silent)
3. 支持项目博客，即开发日志，开发感悟等

**Comment by skyhacker2** [comment]
帅！
