### ISSUE TITLE
Awesome  List

### ISSUE THREAD

**Issue by Jayin** [Jayin/jayin.github.io#42]
[Awesome WPO](https://github.com/davidsonfellipe/awesome-wpo)

> A curated list of Web Performance Optimization. Everyone can contribute here!

[awesome-android-ui](https://github.com/wasabeef/awesome-android-ui)

> A curated list of awesome Android UI/UX libraries 

AndroidDevTools

> 收集整理Android开发所需的Android SDK、开发中用到的工具、Android开发教程、Android设计规范，免费的设计素材等https://github.com/inferjay/AndroidDevTools

移动端开发所需要的一些资源与小技巧

> https://github.com/jtyjty99999/mobileTech

android-best-practices

> android最佳实践https://github.com/futurice/android-best-practices

Android Studio Tips

> https://github.com/pavlospt/Android-Studio-Tips-by-Philippe-Breault

[Remote Debugging on Android with Chrome](https://developer.chrome.com/devtools/docs/remote-debugging)

> 用chrome来远程调试Android WebView
### [betwixt](https://github.com/kdzwinel/betwixt)

> web调试代理，提供chrome dev tool 的界面，推荐！！！！！
## 手册

[PyTab在线手册中心](http://docs.pythontab.com/)
[readthedocs](https://github.com/rtfd/readthedocs.org)
## Python

mkdocs

> Project documentation with Markdown. http://www.mkdocs.org

task schedule & task execution
- https://github.com/dbader/schedule
- https://github.com/pyinvoke/invoke

shell

> A better way to run shell commands in Python.https://shell.readthedocs.org/en/latest/

[fabric](https://github.com/fabric/fabric)

> 远程调用执行
## Javascript

html-minifier  

> Javascript-based HTML compressor/minifier  https://github.com/kangax/html-minifier

fetch. github开源的js请求库

> A window.fetch JavaScript polyfill. fetch https://github.com/github/fetch

[store.js](https://github.com/marcuswestin/store.js)

> 兼容所有浏览器的 LocalStorage 包装器

icono

> 纯CSS实现的icon https://github.com/saeedalipoor/icono

[NProgress.js](http://ricostacruz.com/nprogress/)

> 进度条加载
## Resource

guides

> 各种Guide的汇总 Design and development guides https://github.com/NARKOZ/guides#shell
## PHP

Validation

> 数据验证引擎The most awesome validation engine ever created for PHP 
> http://documentup.com/Respect/Validation
## CSS

[Hover](https://github.com/IanLunn/Hover)

> 大量:hover的动画

**Comment by Jayin** [comment]
资料区
---

awesome-mac-practice
---
mac 新手指南 https://github.com/i5ting/awesome-mac-practice

**Comment by Jayin** [comment]
前端测试/调试
--------------

[Rosin](https://github.com/AlloyTeam/Rosin)
>Fiddler 插件，用于调试移动端页面，腾讯出品

[browser-sync](http://www.browsersync.io/)
> 浏览器同步

**Comment by Jayin** [comment]
Docker &Paas
[dokku](https://github.com/progrium/dokku)

**Comment by fritx** [comment]
cool xuan
