### ISSUE TITLE
Awesome-App-Library

### ISSUE THREAD

**Issue by Jayin** [Jayin/jayin.github.io#43]
[markdown-plus](https://github.com/tylingsoft/markdown-plus)

> 吊炸天的markdown文本编辑

[androidtool-mac](https://github.com/mortenjust/androidtool-mac)

> mac上对android手机截图/录像
### Node

node-notifier https://github.com/mikaelbr/node-notifier

> A Node.js module for sending notifications on native Mac, Windows (post and pre 8) and Linux (or Growl as fallback)

**Comment by jacsonLee** [comment]
diaobao
