### ISSUE TITLE
死就死吧，我知道如果我挖坑不填，你们一定会嘲笑我的！但是，我豁出去啦！

### ISSUE THREAD

**Issue by Jayin** [Jayin/jayin.github.io#44]
### TODO
- [ ] 每日阅读一篇阮一峰的网络日志
- [] 前端技能汇总 Frontend Knowledge Structure http://html5ify.com/fks/
- [ You-Dont-Know-JS](https://github.com/getify/You-Dont-Know-JS)

### 硬性规定
- 每周一技术博文
- ~~每日都去运动(时间允许的话)，游泳/跑步自己选~~

**Comment by fritx** [comment]
nice 深圳码农周末刊

**Comment by skyhacker2** [comment]
nice

**Comment by fritx** [comment]
@skyhacker2 晶总我换号了 求乎follow个

**Comment by fritx** [comment]
Nice！

**Comment by jacsonLee** [comment]
nice！

**Comment by jacsonLee** [comment]
@fritx  我擦 又换号？

**Comment by fritx** [comment]
@jacsonLee 没有 我是说之前换号 这个暂时不换

**Comment by fritx** [comment]
,...

**Comment by fritx** [comment]
妈的 想当年英董还在深圳
