### ISSUE TITLE
【idea】写一个后台应用，每当网站页面有变化时发邮件通知🚀

### ISSUE THREAD

**Issue by Jayin** [Jayin/jayin.github.io#46]
有时候需要关注某些资讯，但又懒得去写爬虫什么的。直接页面有变化就通知自己去查看即可

**Comment by skyhacker2** [comment]
那跟爬虫的区别？

**Comment by Jayin** [comment]
类似爬虫，只是不提取内容，发现有difference(例如文章列表发生变化)，立马发邮件通知🚀

**Comment by fritx** [comment]
假如你用node的话 可以考虑使用nightmare/nixe这种high-level的工具
去访问/观察/处理网页 :smile:

**Comment by fritx** [comment]
一般爬虫还没法解析JS动态加载的内容 所以才有electron的必要？

**Comment by Jayin** [comment]
哈，一般文章都是相对“静态”(文章用后端渲染好) 不是js加载的吧🚀

**Comment by fritx** [comment]
你说的没错 大部分都是静态 所以传统的爬虫才有用武之地
但后来也出现了大量单页应用 尤其是移动端 你得承认他们可都是动态加载的

**Comment by Jayin** [comment]
是哒🚀

**Comment by Jayin** [comment]
已实现：https://visualping.io/
